### PR TITLE
Use SQLite or anything else for discovery cache

### PR DESCRIPTION
**Pull request by adamiak**
Resolves L2B-2601

### CODE REVIEW

**Review by michalsidzej — APPROVED** [review]
LGTM. Haven't tested the SQLite integration, but I was able to use it in `lz-monitoring` without any problems. Please make sure you add changeset to the PR (unless there's a new process in place).

**Review by sdlyy — APPROVED** [review]
Looks decent, we have to battle-test that in practice.
Also, it would be great to have some test suite to seal the implementation

**Review by mateuszradomski — APPROVED** [review]
Looks very nice, gj!

**Comment by adamiak** [comment]
> Looks decent, we have to battle-test that in practice. Also, it would be great to have some test suite to seal the implementation

Definitely. I'll add a story to add tests once we make sure that the approach works for us.

**Pull request merged**
